"""add shipping fields to orders

Revision ID: 4830ab1f329d
Revises: 3f883029c1d1
Create Date: 2026-09-08 15:02:34.619771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4830ab1f329d'
down_revision: Union[str, Sequence[str], None] = '3f883029c1d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_phone', sa.String(length=30), nullable=True))
    op.add_column('orders', sa.Column('shipping_cep', sa.String(length=10), nullable=True))
    op.add_column('orders', sa.Column('shipping_state', sa.String(length=2), nullable=True))
    op.add_column('orders', sa.Column('shipping_city', sa.String(length=150), nullable=True))
    op.add_column('orders', sa.Column('shipping_street', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('shipping_number', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'shipping_number')
    op.drop_column('orders', 'shipping_street')
    op.drop_column('orders', 'shipping_city')
    op.drop_column('orders', 'shipping_state')
    op.drop_column('orders', 'shipping_cep')
    op.drop_column('orders', 'customer_phone')
    # ### end Alembic commands ###
