"""add product type to products

Revision ID: a38792a3c9ad
Revises: bdaf0896137b
Create Date: 2026-09-18 15:57:11.461614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a38792a3c9ad'
down_revision: Union[str, Sequence[str], None] = 'bdaf0896137b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Cria a coluna permitindo NULL temporariamente
    op.add_column(
        'products',
        sa.Column('product_type', sa.String(length=50), nullable=True)
    )

    # Produtos que já existem passam a ser produtos físicos
    op.execute(
        "UPDATE products SET product_type = 'physical' WHERE product_type IS NULL"
    )

    # Depois torna o campo obrigatório
    op.alter_column(
        'products',
        'product_type',
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'product_type')
    # ### end Alembic commands ###
