"""add payment fields to orders

Revision ID: bdaf0896137b
Revises: 4830ab1f329d
Create Date: 2026-09-09 10:08:52.056803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdaf0896137b'
down_revision: Union[str, Sequence[str], None] = '4830ab1f329d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'orders',
        sa.Column(
            'payment_status',
            sa.String(length=50),
            nullable=False,
            server_default='pending'
        )
    )

    op.add_column(
        'orders',
        sa.Column('payment_method', sa.String(length=50), nullable=True)
    )

    op.add_column(
        'orders',
        sa.Column('payment_provider', sa.String(length=50), nullable=True)
    )

    op.add_column(
        'orders',
        sa.Column('payment_reference', sa.String(length=255), nullable=True)
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_reference')
    op.drop_column('orders', 'payment_provider')
    op.drop_column('orders', 'payment_method')
    op.drop_column('orders', 'payment_status')
    # ### end Alembic commands ###
