"""add shipping fields to orders

Revision ID: e9e3be4c0e06
Revises: f60650ccd2ca
Create Date: 2026-09-30 16:01:57.316592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9e3be4c0e06'
down_revision: Union[str, Sequence[str], None] = 'f60650ccd2ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shipping_service_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('shipping_service_name', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('shipping_company', sa.String(length=100), nullable=True))
    op.add_column("orders", sa.Column("shipping_price", sa.Numeric(precision=10, scale=2), nullable=False, server_default="0.00" ))
    op.add_column('orders', sa.Column('shipping_delivery_min', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('shipping_delivery_max', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'shipping_delivery_max')
    op.drop_column('orders', 'shipping_delivery_min')
    op.drop_column('orders', 'shipping_price')
    op.drop_column('orders', 'shipping_company')
    op.drop_column('orders', 'shipping_service_name')
    op.drop_column('orders', 'shipping_service_id')
    # ### end Alembic commands ###
