"""add shipping complement to orders

Revision ID: f03d3c9523b1
Revises: 617422e2ddde
Create Date: 2026-09-26 11:37:45.106557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f03d3c9523b1'
down_revision: Union[str, Sequence[str], None] = '617422e2ddde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shipping_complement', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'shipping_complement')
    # ### end Alembic commands ###
