"""add shipping dimensions to products

Revision ID: fa23eb2508b4
Revises: f03d3c9523b1
Create Date: 2026-09-29 11:32:05.746319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa23eb2508b4'
down_revision: Union[str, Sequence[str], None] = 'f03d3c9523b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('weight', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('products', sa.Column('length', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('width', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('height', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'height')
    op.drop_column('products', 'width')
    op.drop_column('products', 'length')
    op.drop_column('products', 'weight')
    # ### end Alembic commands ###
